### ISSUE TITLE
Bout reply person looks incorrect

### ISSUE THREAD

**Issue by longtimeago** [teamed/at.teamed.io#3]
I've seen several times the case when the message should be from Alice, but it appears to be from another guy.
For example, see this screenshot
![screenshot from 2015-11-13 17 16 56](https://cloud.githubusercontent.com/assets/1388994/11149428/3e588d44-8a2b-11e5-94fb-8d92286eb2f5.png)

IMHO, the message below (http://www.netbout.com/b/36043#msg512998) looks correct. The author is talking to Alice.
But the upper message (http://www.netbout.com/b/36043#msg512999) is weird. The author is talking to himself (using Alise's words!). It looks like the message is published with wrong user name and icon

One more example:
![screenshot from 2015-11-13 17 17 26](https://cloud.githubusercontent.com/assets/1388994/11149429/42286106-8a2b-11e5-9104-8a6206779c9c.png)
http://www.netbout.com/b/36041#msg512992  looks correct
http://www.netbout.com/b/36041#msg512993  looks wrong

This issue is moved from https://github.com/yegor256/netbout/issues/835
and it's still valid

**Comment by yegor256** [comment]
@longtimeago it's fixed already: https://github.com/teamed/at.teamed.io/commit/c2088a8850dc987e90b8e8d880718fe45a4b50d0 You should not see this problem in new invitations for interview
